--CREATE SEQUENCE IF NOT EXISTS task_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE category
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label TEXT,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE task
(
    id          BIGINT NOT NULL,
    title       TEXT,
    description TEXT,
    is_complete BOOLEAN,
    category_id BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);